name: kigot
recipe: symfony
config:
  php: '8.2'
  via: nginx
  webroot: public
services:
  database:
    type: mysql
    portforward: 3307
    creds:
      user: admin
      password: admin
      database: kigo_data
  node:
    type: node:18
    build:
      - yarn install
      - npm install
tooling:
  yarn:
    service: node
  node:
    service: node
  npm:
    service: node

